export enum AccessType {
  WRITEACCESS = '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',
  READACCESS = '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',
  UNAUTHORIZEDACCESS = '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',
}
