export enum AccessType {
  WRITEACCESS = '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',
  READACCESS = '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',
  UNAUTHORIZEDACCESS = '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',
}
